export const TELEGRAM_BOT = {
  PEACOM_BOT: process.env.MONITORING_TELEGRAM_BOT_TOKEN || "6661792776:AAGSCvGgyfjxDk6rWQSUEyJBhdtmaWSM1Ak",
  PEACOM_MONITORING_GROUP: process.env.MONITORING_TELEGRAM_GROUP_ID || "-4249824438",
};
